language: minimal
dist: trusty

addons:
  apt_packages:
    - docker-compose

jobs:
  include:
    - stage: build-run docker-compose
      script:
      - docker-compose --version
      - docker-compose up
addons:
  apt_packages:
    - nginx