dist: trusty

include:
  - os: linux
    addons:
      apt:
        update: true
        packages:
          - docker-compose

jobs:
  include:
    - stage: build-run docker 
      script:
      - docker-compose --vesion
      - docker --version
      - docker-compose up
