# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: battleship-server/battleship # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    ports:
      - "9090:9090" # Forward the exposed port 9090 on the container to port 9090 on the host machine
    restart: always
    depends_on: 
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/battleship?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: battleship
      SPRING_DATASOURCE_PASSWORD: battleship     
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend
    image:  isergeyam/battleship_server

  # Frontend Service 
  app-client:
    build:
      context: battleship-client # Use an image built from the specified dockerfile in the `polling-app-client` directory.
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:9090/api
    ports:
      - "8080:80" # Forward the exposed port 8080 on the container to port 80 on the host machine
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  
    image:  isergeyam/battleship_client


  # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: battleship
      MYSQL_USER: battleship
      MYSQL_PASSWORD: battleship
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend  
    image:  isergeyam/battleship_db
  
# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:    

